#!/usr/bin/env python3

# Import the necessary libraries
import time
import math
from ev3dev2.motor import *
from ev3dev2.sound import Sound
from ev3dev2.button import Button
from ev3dev2.sensor import *
from ev3dev2.sensor.lego import *
from ev3dev2.sensor.virtual import *

# Create the sensors and motors objects
motorA = LargeMotor(OUTPUT_A)
motorB = LargeMotor(OUTPUT_B)
left_motor = motorA
right_motor = motorB
tank_drive = MoveTank(OUTPUT_A, OUTPUT_B)
steering_drive = MoveSteering(OUTPUT_A, OUTPUT_B)

spkr = Sound()
btn = Button()
radio = Radio()

color_sensor_in1 = ColorSensor(INPUT_1)
ultrasonic_sensor_in2 = UltrasonicSensor(INPUT_2)
ultrasonic_sensor_in3 = UltrasonicSensor(INPUT_3)
ultrasonic_sensor_in4 = UltrasonicSensor(INPUT_4)
gyro_sensor_in5 = GyroSensor(INPUT_5)
gps_sensor_in6 = GPSSensor(INPUT_6)

motorC = LargeMotor(OUTPUT_C) # Magnet

# Here is where your code starts
import random

nahodna_ciselna_hodnota = None
farba = None
zelena_plat_ = None
modr_C3_A1_l___C4_8D1 = None
zlte_plat_ = None
modr_C3_A1_l___C4_8D2 = None
oranzova_pla_ = None
modr_C3_A1_l___C4_8D3 = None
cervene_plat_ = None
modr_C3_A1_l___C4_8D4 = None
modr_C3_A1_l___C4_8D5 = None
modr_C3_A1_r___C4_8D1 = None
modr_C3_A1_r___C4_8D2 = None
modr_C3_A1_r___C4_8D3 = None
modr_C3_A1_r___C4_8D4 = None
modr_C3_A1_r___C4_8D5 = None
def hladat_ptiestory_pre_polozenie_vod_C3_ADka():
    global nahodna_ciselna_hodnota, farba, zelena_plat_, modr_C3_A1_l___C4_8D1, zlte_plat_, modr_C3_A1_l___C4_8D2, oranzova_pla_, modr_C3_A1_l___C4_8D3, cervene_plat_, modr_C3_A1_l___C4_8D4, modr_C3_A1_l___C4_8D5, modr_C3_A1_r___C4_8D1, modr_C3_A1_r___C4_8D2, modr_C3_A1_r___C4_8D3, modr_C3_A1_r___C4_8D4, modr_C3_A1_r___C4_8D5
    zelena_plat_ = gps_sensor_in6.x == -40 and gps_sensor_in6.y == -127
    zlte_plat_ = gps_sensor_in6.x == 44 and gps_sensor_in6.y == -127
    oranzova_pla_ = gps_sensor_in6.x == 42 and gps_sensor_in6.y == 129
    cervene_plat_ = gps_sensor_in6.x == -44 and gps_sensor_in6.y == -129


hladat_ptiestory_pre_polozenie_vod_C3_ADka()
# Describe this function...
def pohybovanie_atonmnym_sposobom_ku_farebnym_plocham_pre_uschovu_vod_C3_ADka():
    global nahodna_ciselna_hodnota, farba, zelena_plat_, modr_C3_A1_l___C4_8D1, zlte_plat_, modr_C3_A1_l___C4_8D2, oranzova_pla_, modr_C3_A1_l___C4_8D3, cervene_plat_, modr_C3_A1_l___C4_8D4, modr_C3_A1_l___C4_8D5, modr_C3_A1_r___C4_8D1, modr_C3_A1_r___C4_8D2, modr_C3_A1_r___C4_8D3, modr_C3_A1_r___C4_8D4, modr_C3_A1_r___C4_8D5
    gyro_sensor_in5.reset()
    while not (cervene_plat_ or oranzova_pla_ or zlte_plat_ or zelena_plat_):
        nahodna_ciselna_hodnota = random.randint(-130, 45)
        if nahodna_ciselna_hodnota == 0:
            pass
        elif False:
            pass
        elif False:
            pass
        elif False:
            pass
# Describe this function...
def cesta_k_vod_C3_ADku():
    global nahodna_ciselna_hodnota, farba, zelena_plat_, modr_C3_A1_l___C4_8D1, zlte_plat_, modr_C3_A1_l___C4_8D2, oranzova_pla_, modr_C3_A1_l___C4_8D3, cervene_plat_, modr_C3_A1_l___C4_8D4, modr_C3_A1_l___C4_8D5, modr_C3_A1_r___C4_8D1, modr_C3_A1_r___C4_8D2, modr_C3_A1_r___C4_8D3, modr_C3_A1_r___C4_8D4, modr_C3_A1_r___C4_8D5
    gyro_sensor_in5.reset()
    modr_C3_A1_l___C4_8D1 = gps_sensor_in6.x == -127 and gps_sensor_in6.y == 42
    modr_C3_A1_l___C4_8D2 = gps_sensor_in6.x == -127 and gps_sensor_in6.y == -1
    modr_C3_A1_l___C4_8D3 = gps_sensor_in6.x == -86 and gps_sensor_in6.y == -1
    modr_C3_A1_l___C4_8D4 = gps_sensor_in6.x == -127 and gps_sensor_in6.y == -42
    modr_C3_A1_l___C4_8D5 = gps_sensor_in6.x == -127 and gps_sensor_in6.y == -84
    modr_C3_A1_r___C4_8D1 = gps_sensor_in6.x == 127 and gps_sensor_in6.y == 84
    modr_C3_A1_r___C4_8D2 = gps_sensor_in6.x == 127 and gps_sensor_in6.y == 42
    modr_C3_A1_r___C4_8D3 = gps_sensor_in6.x == 127 and gps_sensor_in6.y == 1
    modr_C3_A1_r___C4_8D4 = gps_sensor_in6.x == 127 and gps_sensor_in6.y == 1
    modr_C3_A1_r___C4_8D5 = gps_sensor_in6.x == -40 and gps_sensor_in6.y == -42
